## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - CLUSTER-CLEANUP

konvoy-cluster:
  stage: CLUSTER-SETUP
  tags: 
    - k8s-konvoy 
  script:
    - chmod 755 ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup
    - ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup
  artifacts:
    paths:
      - config/

konvoy-cleanup:
  when: always
  stage: CLUSTER-CLEANUP
  dependencies: 
    - konvoy-cluster
  tags: 
    - k8s-konvoy 
  script:
    - chmod 755 ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-cleanup
    - ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-cleanup
