## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - CLUSTER-CLEANUP

konvoy-cluster:
  image: ranjnshashank855/konvoy:v15
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup
    - sudo ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup/cluster-setup
  artifacts:
    paths:
      - config/

konvoy-cleanup:
  image: ranjnshashank855/konvoy:v15
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-setup
    - sudo ./openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/cluster-cleanup
